### ISSUE TITLE
Missing Composer autoload rule

### ISSUE THREAD

**Issue by clue** [seregazhuk/php-react-memcached#1]
Nice library! Unless I'm missing something obvious, it looks like the following should probably be in `autoload` instead of `autoload-dev`:

https://github.com/seregazhuk/php-react-memcached/blob/7ad1505ecdf531b4837821d228da36aca1986112/composer.json#L26

**Comment by seregazhuk** [comment]
Thank you! Yes, sure! I've missed it.
