### ISSUE TITLE
Connection auto-recover

### ISSUE THREAD

**Issue by kelunik** [seregazhuk/php-react-memcached#3]
Currently the `Factory` creates one connection, but as soon as the connection breaks once, there's no reconnect mechanism. I hereby propose dropping the `Factory` and instead handing the connect logic lazily in `Client`. If one request fails due to a connection failure, further requests can trigger a reconnect and can be resent.

**Comment by seregazhuk** [comment]
I see. How should the api look like? Is it normal to store all pending requests until the connection is established? For example, I can implement something like this:

```php
$client->connect('localhost:11211');
$client->set('example', 'Hello world');
$client->get('example')->then(function ($data) {
    echo $data . PHP_EOL; // Hello world
});
```

Here `set` and `get` commands will be executed after the client is connected. The client code even doesn't know the connection status. If it was broken we try to reconnect and then execute all pending queries.

But if the client code is responsible for reconnecting, where to put this code? Now, when the connection is closed, all pending promises will be rejected, so should I add a rejected handler to all of them and reconnect?

```php
$client->set('example', 'Hello world')
    ->then(null, function(ConnectionClosedException $e) use ($client) {
        $client->connect('localhost:11211');
});
```
But with this approach how to deal with a situation when I want to close the connection manually and don't want to reconnect.

**Comment by kelunik** [comment]
@seregazhuk All libraries I wrote handle this by lazy-connecting once there's the first command. If the connection breaks, all pending queries are usually failed. A new query attempts a reconnect and is sent once the connection is established, see e.g. https://github.com/amphp/redis. They explicitly do not provide a `connect` method.

> But with this approach how to deal with a situation when I want to close the connection manually and don't want to reconnect.

Do you have a use case for that? If you need that, you could just fail all future queries immediately.

**Comment by seregazhuk** [comment]
No use cases, just thoughts. Of course all these nested callbacks don't look nice. When you have a connection promise and inside that you start performing queries. But what are the benefits of hiding connection logic from the client code? I can't know if the client has connected successfully until I call any command on it?

**Comment by kelunik** [comment]
> Of course all these nested callbacks don't look nice.

Coroutines to the rescue. :stuck_out_tongue_winking_eye: 

> But what are the benefits of hiding connection logic from the client code?

Less state to manage. You don't want to create a new client every time the connection breaks. And you don't want to check on every client usage whether the connection broke. Having a connect mechanism like that is totally fine for short scripts, but having to handle it everywhere is a pain for long running apps like HTTP servers that use the client in multiple responders spanning multiple requests.

> I can't know if the client has connected successfully until I call any command on it?

Why do you want to know that? Do you care about it for an HTTP client? It only matters if it fails, in which case you'll get a connection error for the query.

**Comment by seregazhuk** [comment]
> Coroutines to the rescue. 😜

Yes, I keep an eye on [Amp](https://amphp.org) :sunglasses: and it looks interesting 👍 

You are right about creating a new client every time the connection breaks. I've looked at your redis library. If I'm not mistaken it is hidden in the `Connection` class. Every time you call `send()` method, you simply check the connection. I'll try to use this approach in my library. Thanks for all your suggestions)

**Comment by seregazhuk** [comment]
@kelunik I've implemented connection auto-recover. I will be very grateful if you look at the PR #4 and provide any feedback. The code now looks much cleaner without this *connection callback* that contains all other calls to the client. 

I'm still not sure about the factory. Keep it or hardcode all dependencies inside the client's constructor. And actually the factory is not the factory, there is no logic inside of it, may be rename it to `Builder`?
